spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/jewellery
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: true
    properties:
      org:
        hibernate:
          envers:
            audit_table_suffix: _AUDIT
